# For setting user 
ARG USER_ID
ARG GROUP_ID
RUN echo "USER_ID=$USER_ID, GROUP_ID=$GROUP_ID"
RUN addgroup --gid $GROUP_ID docker_user
RUN adduser --disabled-password --gecos '' --uid $USER_ID --gid $GROUP_ID docker_user

# Create workspace directory
RUN mkdir -p /workspace && chown -R docker_user:docker_user /workspace

# Install rust
USER docker_user
RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
ENV PATH=/home/docker_user/.cargo/bin:$PATH

# Update rust nightly
RUN rustup update nightly
RUN rustup component add rustfmt --toolchain nightly

# Install rye
ENV PATH=/home/docker_user/.rye/shims:$PATH
RUN curl -sSf https://rye.astral.sh/get | RYE_VERSION="0.41.0" RYE_INSTALL_OPTION="--yes" bash

# Install maturin
RUN rye install maturin

# Clean up unwanted packages
USER root
RUN pip uninstall -y numba cudf cugraph cugraph-dgl cugraph-pyg cugraph-service-server cuml dask-cuda librosa \
    dask-cudf raft-dask cupy-cuda12x thinc nvidia-modelopt
RUN sed -i '/numpy/d' /etc/pip/constraint.txt
RUN sed -i '/torch/d' /etc/pip/constraint.txt
# RUN sed -i '/torch>=2.5.1/d' pyproject.toml
RUN pip install --upgrade "numpy>=2.1.1"

USER docker_user
WORKDIR /workspace

# Set paths
ENV PATH=/home/docker_user/.venv/bin:/home/docker_user/.cargo/bin:/home/docker_user/.rye/shims:$PATH
