import numpy as np
import numpy.typing as npt

def hello_world() -> str: ...
def hello_numpy_world() -> npt.NDArray[np.float32]: ...

class ParallelEnv:
    def __init__(self, n_envs: int) -> None: ...
    def seq_step(
        self, actions: npt.NDArray[np.int_]
    ) -> tuple[npt.NDArray[np.float32], list[tuple[int, int]], list[bool]]: ...
